#!/usr/bin/env bash
# shellcheck source=scripts/common.sh
source "$(dirname "$0")/common.sh"
guest_only
log "Validate Pi 5 full KMS and configure first login"
# Keep the official image's graphics settings; reject unsupported changes.
python3 - <<'PY'
import sys
from pathlib import Path
sys.path.insert(0, '/opt/piforge/scripts')
from boot_config import validate_boot
validate_boot(Path('/boot/firmware'))
PY
# Upstream selects RGUI and the GL driver; preserve its generated settings.
install -m 755 "$PIFORGE_ROOT/scripts/firstboot.sh" /usr/local/sbin/piforge-firstboot
install -m 644 "$PIFORGE_ROOT/configs/piforge-firstboot.service" /etc/systemd/system/piforge-firstboot.service
# The pinned base enables a tty8 dialog which can rename pi and break paths
# generated by RetroPie. Replace that dialog with our fixed-account prompt.
systemctl disable userconfig.service
systemctl enable getty@tty1.service
systemctl enable piforge-firstboot.service
rm -f /etc/sudoers.d/010_pi-nopasswd
printf '\nPiForge: log in as pi, then run emulationstation on the local console.\n' >> /etc/issue
